# Generated by Django 3.1 on 2024-06-26 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('employement_type', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('skills_required', models.JSONField(max_length=200)),
                ('application_start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('application_end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='manager.hrmanager')),
            ],
        ),
    ]
