# Generated by Django 3.1 on 2024-06-17 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('employement_type', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('skills_required', models.JSONField(max_length=200)),
                ('application_start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('application_end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('job_applications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
    ]
