version: '3.8'
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - MONGO_DB_NAME=master
      - MONGO_URI=mongodb+srv://jimitparmar:L5BU33aP3zFsaNSJ@hirasysdb.q3uiqps.mongodb.net/master?retryWrites=true&w=majority