# Generated by Django 3.1 on 2024-06-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_to_job', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('In Progress', 'In Progress'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Offered', 'Offered')], default='Applied', max_length=20)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('cover_letter', models.CharField(max_length=500)),
                ('interview_feedback', models.CharField(max_length=200)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job_name', models.CharField(max_length=300)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.candidate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ('-application_date',),
            },
        ),
    ]
