# Generated by Django 3.1 on 2024-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
