# Generated by Django 3.1 on 2024-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20240618_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
