# Generated by Django 3.1 on 2024-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20240619_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate_id',
            field=models.IntegerField(),
        ),
    ]
