# Generated by Django 3.1 on 2024-06-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_candidate_application'),
        ('application', '0003_auto_20240619_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='candidate_id',
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.candidate'),
        ),
    ]
