# Generated by Django 4.2.5 on 2024-09-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
