# Generated by Django 4.2.5 on 2024-09-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_id'),
        ('company', '0005_alter_company_id'),
    ]

    operations = [
    ]
