# Generated by Django 3.1 on 2024-06-19 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^\\+?1?\\d{9,10}$')])),
                ('education', models.JSONField(max_length=255)),
                ('experiences', models.JSONField(blank=True, max_length=300, null=True)),
                ('skills', models.JSONField(blank=True, max_length=300, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
    ]
