# Generated by Django 3.0.5 on 2024-06-12 07:52

import base.models.candidate
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240608_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^\\+?1?\\d{9,10}')])),
                ('education', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('experiences', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('skills', djongo.models.fields.ArrayField(model_container=base.models.candidate.Skills)),
                ('applications', djongo.models.fields.ArrayField(model_container=base.models.candidate.Application)),
            ],
        ),
    ]
