# Generated by Django 4.2.5 on 2024-09-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_candidate_profile_pic_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experiences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
