# Generated by Django 3.1 on 2024-06-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('base', '0004_auto_20240615_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.application'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.JSONField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='experiences',
        ),
        migrations.AddField(
            model_name='candidate',
            name='experiences',
            field=models.JSONField(blank=True, max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
