# Generated by Django 3.1 on 2024-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240617_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
