# Generated by Django 4.2.5 on 2024-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmanager',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='manager/profile_pic'),
        ),
        migrations.AlterField(
            model_name='hrmanager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
