# Generated by Django 4.2.5 on 2024-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_hrmanager_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrmanager',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='hrmanager',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
