# Generated by Django 4.2.5 on 2024-09-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_socials'),
        ('manager', '0005_remove_hrmanager_profile_pic_hrmanager_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmanager',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
