# Generated by Django 4.2.5 on 2024-09-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_id'),
        ('manager', '0007_remove_hrmanager_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmanager',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
